---
title: "Tidyverse"
author: "**Milan Bhardwaj**, *Matr. Nr. 562289*"
---

# Challenge 1: Analyze the sales by location (state) with a bar plot.
```{r}
library(tidyverse)
library(readxl)
```

```{r}
# Import data
bikes_tbl <- read_excel(path = "/Users/milan/Documents/study/SEM4/BDSB/main/data/ds_data/01_bike_sales/01_raw_data/bikes.xlsx")
orderlines_tbl <- read_excel(path = "/Users/milan/Documents/study/SEM4/BDSB/main/data/ds_data/01_bike_sales/01_raw_data/orderlines.xlsx")
bikeshops_tbl <- read_excel(path = "/Users/milan/Documents/study/SEM4/BDSB/main/data/ds_data/01_bike_sales/01_raw_data/bikeshops.xlsx")
```

```{r}
# 4.0 Joining Data
bike_orderlines_joined_tbl <- orderlines_tbl %>%
  left_join(bikes_tbl, by = c("product.id" = "bike.id")) %>%
  left_join(bikeshops_tbl, by = c("customer.id" = "bikeshop.id"))
# bike_orderlines_joined_tbl %>% glimpse()

bike_orderlines_wrangled_tbl <- bike_orderlines_joined_tbl %>%
  
  separate(col = location, into = c("city", "state"), sep = ",") %>%
  mutate(total.price = price * quantity) %>%
  select(-...1, -gender) %>%
  select(-ends_with(".id")) %>%
  
  bind_cols(bike_orderlines_joined_tbl %>% select(order.id)) %>% 
  select(order.id, contains("order"), contains("model"), contains("category"),
         price, quantity, total.price,
         everything()) %>%
  rename(bikeshop = name) %>%
  set_names(names(.) %>% str_replace_all("\\.", "_"))

```

```{r}
# Sales by location ----
library(lubridate)
sales_by_loc <- bike_orderlines_wrangled_tbl %>%
  
  select(order_date, state, total_price) %>%
  mutate(year = year(order_date)) %>%
  group_by(state) %>% 
  summarize(sales = sum(total_price)) %>%
  
  mutate(sales_text = scales::dollar(sales, big.mark = ".", decimal.mark = ",", prefix = "EUR "))

sales_by_loc
```

# Step 2 - Visualize

```{r plot, fig.width=8, fig.height=5}
sales_by_loc %>%
  
  ggplot(aes(x = state, y = sales)) +
  
  geom_col(fill = "#354555") + 
  geom_label(aes(label = sales_text)) + 
  geom_smooth(method = "lm", se = FALSE) + 
  
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", decimal.mark = ",", prefix = "EUR ")) +
  labs(title = "Revenue by location", x = "State", y = "Revenue") + theme(axis.text.x = element_text(angle = 45, hjust = 1))

```

```{r}
# Sales by Year and location 
sales_by_year_location_tbl <- bike_orderlines_wrangled_tbl %>%
  select(order_date, total_price, state) %>%
  mutate(year = year(order_date)) %>%
  
  group_by(year, state) %>%
  summarise(sales = sum(total_price)) %>%
  ungroup() %>%
  
  mutate(sales_text = scales::dollar(sales, big.mark = ".", decimal.mark = ",", prefix = "EUR "))

sales_by_year_location_tbl  
```
## 2. Visualization- 12 Plots
```{r}

sales_by_year_location_tbl %>%
  ggplot(aes(x = year, y = sales, fill = state)) +
  geom_col() +
  facet_wrap(~ state) +
  
  scale_y_continuous(labels = scales::dollar_format(big.mark = ".", decimal.mark = ",", prefix = "EUR ")) +
  labs(
    title = "Revenue by year and state",
    fill = "state"
  )+ theme(axis.text.x = element_text(angle = 45, hjust = 1))

```